### ISSUE TITLE
Using the new SumUpExperimentalAPI.prepareForCheckout(boolean retainBLEConnection)

### ISSUE THREAD

**Issue by gabrielsolomon** [PurpleSoftSrl/sumup_flutter_plugin#32]
Hello,

Is there a plan to integrate the new SumUpExperimentalAPI.prepareForCheckout(boolean retainBLEConnection) ?

Thank you very much!

**Comment by sstasi95** [comment]
Hi,

Yes, but I'd rather wait for it to become stable before integrating it in the plugin. Do you need it now?

**Comment by gabrielsolomon** [comment]
I would like to find a way to remember the pos and not require the selection on each start.
I am curious to try and see if the retainBLEConnection will also have this side effect :D

**Comment by sstasi95** [comment]
I added it in 'experimental' branch. You can try it by adding these lines to your pubspec:
```yaml
sumup: 
  git: 
    url: https://github.com/PurpleSoftSrl/sumup_flutter_plugin.git
    ref: experimental
```

Let me know if you see any improvement.
